# Generated by Django 5.1.4 on 2025-11-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_home2_home3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='images/')),
                ('audio', models.FileField(upload_to='audio/')),
                ('video', models.FileField(upload_to='videos/')),
                ('pdf', models.FileField(upload_to='pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.RemoveField(
            model_name='home3',
            name='title',
        ),
        migrations.AddField(
            model_name='home2',
            name='email',
            field=models.EmailField(default='other', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home3',
            name='email',
            field=models.EmailField(default='other', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home2',
            name='subject',
            field=models.CharField(choices=[('complaint', 'شکایت'), ('question', 'سوال'), ('criticism', 'انتقاد'), ('other', 'سایر')], max_length=50),
        ),
    ]
