# Generated by Django 5.1.4 on 2025-11-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_home1_login_delete_message_remove_home3_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home1',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='home1',
            name='images',
        ),
        migrations.RemoveField(
            model_name='home1',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='home1',
            name='video',
        ),
        migrations.AddField(
            model_name='home1',
            name='file',
            field=models.FileField(default='', upload_to='uploades/'),
        ),
    ]
